"""empty message

Revision ID: 9a461fb8441a
Revises: cd5a541478cb
Create Date: 2024-06-22 01:53:33.714710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a461fb8441a'
down_revision: Union[str, None] = 'cd5a541478cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('core_value', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('values')
    # ### end Alembic commands ###
