"""empty message

Revision ID: c63cd07ec4c3
Revises: a33a69457947
Create Date: 2024-06-17 01:58:50.045853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c63cd07ec4c3'
down_revision: Union[str, None] = 'a33a69457947'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('values', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('values', 'thread_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('values', sa.Column('thread_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('values', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
